### ISSUE TITLE
System.AccessViolationException: Could not read bytes from 00000004 [299]!

### ISSUE THREAD

**Issue by czullo** [aash/HBRelog#8] opened 2015-08-25 18:01 UTC
[08/25/2015 20:00:18] System.AccessViolationException: Could not read bytes from 00000004 [299]!
   w GreyMagic.ExternalProcessReader.ReadBytes(IntPtr address, Int32 count, Boolean isRelative) w d:\Pobrane\HBRelog-master\HBRelog-master\Libs\GreyMagic\ExternalProcessReader.cs:wiersz 126
   w GreyMagic.ExternalProcessReader.Read[T](IntPtr address, Boolean isRelative) w d:\Pobrane\HBRelog-master\HBRelog-master\Libs\GreyMagic\ExternalProcessReader.cs:wiersz 195
   w HighVoltz.HBRelog.WoW.Lua.LuaTable..ctor(ExternalProcessReader memory, IntPtr address) w d:\Pobrane\HBRelog-master\HBRelog-master\WoW\Lua\LuaTable.cs:wiersz 19
   w HighVoltz.HBRelog.WoW.Lua.LuaTValue.get_Table() w d:\Pobrane\HBRelog-master\HBRelog-master\WoW\Lua\LuaTValue.cs:wiersz 47
   w HighVoltz.HBRelog.WoW.FrameXml.UIObject.<GetUIObjects>d__2.MoveNext() w d:\Pobrane\HBRelog-master\HBRelog-master\WoW\FrameXml\UIObject.cs:wiersz 168
   w System.Linq.Enumerable.<OfTypeIterator>d__1`1.MoveNext()
   w System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   w System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   w System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   w HighVoltz.HBRelog.WoW.States.LoginWowState.HandleAccountSelectionDialog() w d:\Pobrane\HBRelog-master\HBRelog-master\WoW\States\LoginWowState.cs:wiersz 314
   w HighVoltz.HBRelog.WoW.States.LoginWowState.Run() w d:\Pobrane\HBRelog-master\HBRelog-master\WoW\States\LoginWowState.cs:wiersz 91
   w HighVoltz.HBRelog.FiniteStateMachine.FiniteStateMachine.Engine.Pulse() w d:\Pobrane\HBRelog-master\HBRelog-master\FiniteStateMachine\Engine.cs:wiersz 41
   w HighVoltz.HBRelog.WoW.WowManager.Pulse() w d:\Pobrane\HBRelog-master\HBRelog-master\WoW\WowManager.cs:wiersz 317
   w HighVoltz.HBRelog.TaskManager.Pulse() w d:\Pobrane\HBRelog-master\HBRelog-master\TaskManager.cs:wiersz 62
   w HighVoltz.HBRelog.HbRelogManager.DoWork() w d:\Pobrane\HBRelog-master\HBRelog-master\HBRelogManager.cs:wiersz 125

**Comment by aash** [comment] 2015-08-25 18:16
Close as duplicate of #5. BTW I'm working on fix for #5, got several ideas need to check them.

**Closed as completed by aash** 2015-08-25 18:16 UTC
Labels: duplicate
